server:
  port: 9040

spring:


  kafka:
    consumer:
      bootstrap-servers: localhost:29092
      group-id: application-service-group
      auto-offset-reset: earliest
      properties:
        spring.json.use.type.headers: false

